:Author: john_randolph
:Email: john_randolph@brown.edu
:Date: 01/29/2019
:Revision: version alpha
:License: Public Domain

= Project: {CrapTracker}

Describe your project

An arduino setup for measuring weight differences

== Step 1: Assemble the circuit

Assemble the circuit following the breakout guide in this link:
https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide

Eventually, this will be prepackaged as one product

== Step 2: Install the code

Upload "LoadCellDemo2_copy.ino" to the board

== Step 3: Run the code

Run the code and observe the weight measurements.
The Serial will print a raw weight value several times every second
Commands:
'c': tares the scale
'1': prints the current time
'2': prints the last 100 raw weight values
'3': prints the last hundred average weights, each being an average
	 of a hundred raw values

=== Folder structure

....
 CrapTracker                	=> Arduino sketch folder
  ├── LoadCellDemo_copy.ino     => main Arduino file
  └── ReadMe.adoc         		=> this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact John Randolph <john_randolph@brown.edu>

=== Bill of Materials needed for the project

|===
| ID | Part name          | Part number | Quantity
| -- | Mini load cell     | TAL221      | 1   
| -- | Load Cell Aplifier | HX711       | 1    
| -- | Arduino Uno        | A000066     | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
